"use strict";

function loadSprites(){

	let fuzzTemplate = new FuzzTemplate(document.getElementById("fuzz-template"), 1, 1);

	let spritemap = new SpriteMap();
	spritemap.addSprites(
		document.getElementById("spritemap"),
		{
			player: {x: 0, y: 0, layer: "creatures"},
			sage: {x: 1, y: 0},
			frog: {x: 3, y: 0, layer: "creatures"},
			worm: {x: 4, y: 0, layer: "creatures"},
			fireplace: {x: 2, y: 7},
			ashplace: {x: 3, y: 7},
			fire: {x: 4, y: 7},
			markstone: {x: 5, y: 7},
			worktable: {x: 6, y: 7},
			altar: {x: 7, y: 7},
			grass1: {x: 0, y: 1, layer: "ground"},
			grass2: {x: 1, y: 1, layer: "ground"},
			grass3: {x: 2, y: 1, layer: "ground"},
			dirt: {x: 3, y: 1, layer: "ground"},
			deadleaves: {x: 4, y: 1, layer: "ground"},
			rockfloor: {x: 5, y: 1, layer: "ground"},
			moss: {x: 6, y: 1, layer: "ground"},
			water: {x: 0, y: 2, border: "#226", layer: "base"},
			stonefloor: {x: 1, y: 2, layer: "base"},
			woodwall: {x: 3, y: 2, border: "#220", layer: "base"},
			wall: {x: 4, y: 2, border: "#222", layer: "base"},
			rock: {x: 5, y: 2, border: "#222", layer: "base"},
			rockmid: {x: 7, y: 2, border: "#222", layer: "base"},
			" ": {x: 7, y: 2},
			rush: {x: 0, y: 3},
			pitcherplant: {x: 1, y: 3},
			reed: {x: 2, y: 3},
			flower: {x: 3, y: 3},
			densegrass: {x: 4, y: 3, layer: "ground"},
			gravel: {x: 5, y: 3},
			shrub: {x: 6, y: 3},
			bush: {x: 7, y: 3},
			tree: {x: 3, y: 5, wide: true},
			oldtree: {x: 5, y: 5},
			oldtreetinder: {x: 6, y: 5},
			youngtree: {x: 1, y: 5},
			sapling: {x: 0, y: 5},
			pebble: {x: 0, y: 6},
			stone: {x: 1, y: 6},
			stick: {x: 2, y: 6},
			plantedseed: {x: 0, y: 8},
			seedling: {x: 1, y: 8},
			greenstem: {x: 2, y: 8},
			brownstem: {x: 3, y: 8},
			youngleafplant: {x: 4, y: 8},
			leafplant: {x: 5, y: 8},
			discleaf: {x: 6, y: 8},
			seedingdiscleaf: {x: 7, y: 8},
			youngknifeplant: {x: 4, y: 9},
			knifeplant: {x: 5, y: 9},
			knifeleaf: {x: 6, y: 9},
			seedingknifeleaf: {x: 7, y: 9},
			younghardplant: {x: 0, y: 9},
			hardplant: {x: 1, y: 9},
			hardwoodstick: {x: 2, y: 9},
			seedinghardwood: {x: 3, y: 9},
			hardknifeplant: {x: 5, y: 10},
			harddiscplant: {x: 4, y: 10},
			sawplant: {x: 3, y: 10},
			hardwoodknife: {x: 1, y: 10},
			hardwoodtable: {x: 0, y: 10},
			sawblade: {x: 2, y: 10},
			sawtable: {x: 6, y: 10},
		},
		8,
		fuzzTemplate
	);
	return spritemap;
}
